const path = require('path')
const favicon = require('serve-favicon')
const compress = require('compression')
const cors = require('cors')
const helmet = require('helmet')
const logger = require('winston')
const feathers = require('@feathersjs/feathers')
const configuration = require('@feathersjs/configuration')
const express = require('@feathersjs/express')
const socketio = require('@feathersjs/socketio')
const middleware = require('./middleware')
const services = require('./services')
const appHooks = require('./app.hooks')
const channels = require('./channels')
const mongoose = require('./mongoose')
const app = express(feathers())

app.configure(configuration())
app.use(cors())
app.use(helmet())
app.use(compress())
app.use(express.json())
app.use(express.urlencoded({extended: true}))
app.use(favicon(path.join(app.get('public'), 'favicon.ico')))
app.use('/', express.static(app.get('public')))
app.configure(express.rest())
app.configure(socketio())
app.configure(mongoose)
app.configure(middleware)
app.configure(services)
app.configure(channels)
app.use(express.notFound())
app.use(express.errorHandler({logger}))

app.hooks(appHooks)

module.exports = app
